Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false
