# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] || 'historikc' %>
  username: <%= ENV['RDS_USERNAME'] || 'root' %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] || '0.0.0.0' %>
  port: <%= ENV['RDS_PORT'] || 3306 %>

development:
  <<: *default

test:
  <<: *default
  database: historikc_test

production:
  <<: *default
